import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type VentureDocument = Venture & Document;

// Individual collaborator in a venture
class Collaborator {
  @Prop({ required: true })
  walletAddress: string;

  @Prop({ required: true, min: 0, max: 100 })
  sharePercentage: number;

  @Prop({ default: false })
  hasAccepted: boolean; // Whether collaborator accepted the venture invitation
}

@Schema({ timestamps: true })
export class Venture {
  // Link to the post this venture is for
  @Prop({ type: Types.ObjectId, ref: 'Post', required: true, unique: true })
  postId: Types.ObjectId;

  // Who initiated/created this venture
  @Prop({ required: true, index: true })
  initiator: string;

  // All collaborators with their share percentages
  @Prop({ type: [Collaborator], required: true })
  collaborators: Collaborator[];

  // Status of the venture
  @Prop({ 
    type: String, 
    enum: ['pending', 'active', 'rejected', 'completed'],
    default: 'pending'
  })
  status: string;

  // Total revenue generated by this venture (in tokens)
  @Prop({ default: 0 })
  totalRevenueGenerated: number;

  // Total number of revenue splits executed
  @Prop({ default: 0 })
  totalSplits: number;

  // Optional: Description of the collaboration
  @Prop()
  description?: string;
}

export const VentureSchema = SchemaFactory.createForClass(Venture);

// Indexes for efficient queries
VentureSchema.index({ initiator: 1, createdAt: -1 });
VentureSchema.index({ 'collaborators.walletAddress': 1 });
VentureSchema.index({ status: 1 });
